source: .
destination: ./_site
plugins_dir: ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes
drafts_dir: ./_drafts
posts_dir: ./_posts

gems: [jekyll-paginate]
title: CS @ HEROES Academy
description: ""
port: 43203
url: "http://cs.njgifted.org"
github_username:  braingineer
language: en_US
paginate: 10
paginate_path: "/page/:num/"
permalink: "/:month/:day/:title/"
show_drafts: true

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown

kramdown:
  input: GFM
